### ISSUE TITLE
Starwhale Runtime 2.0

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#741]
**Current Behavior**

```yaml
mode: venv
name: pytorch
pip_req: requirements.txt
python_version: '3.9'
starwhale_version: ''
```

**Proposed Behavior**

```yaml
version: 2.0

name: pytorch  #required: runtime name
mode: venv     #optional, default venv

environment:
  arch: noarch     #optional, x86/aarch64/noarch
  os: linux            #optional 
  python: 3.8.13  #optional, python version
  cuda: xxx          #optional, cuda version

dependencies:          # optional
  - requirements.txt   

  - conda.yaml         
  - conda:
     - package==version   # conda python version
  - pip:
     - package==version   # python package version
  - wheels:
     - xxx.whl            # wheel package uri(local or remote)
  - files:
     - name: xxx          
       src: xxx          
       dest: yyy          
       pre: cmd           # hook: pre command
       post: cmd          # hook: post command
       
 hooks:          # optional
   pre: xxx      # restore bash
   post: yyy     # restore bash
   
 configs:        # optional
   docker:       
      registry: ghcr.io
      image: star-whale/starwhale
   conda:
      channels:
        - conda-forge  # conda channels
   pip:
      index_url: xx
      external_url: xx
      trusted_hosts: xx
```

**Subtasks**
- [x] https://github.com/star-whale/starwhale/issues/742
- [x] https://github.com/star-whale/starwhale/issues/744
- [x] https://github.com/star-whale/starwhale/issues/745
- [x] https://github.com/star-whale/starwhale/issues/747
- [x] https://github.com/star-whale/starwhale/issues/749
- [x] Tune activate
    - [x] https://github.com/star-whale/starwhale/issues/572
    - [x] https://github.com/star-whale/starwhale/issues/752
- [x] https://github.com/star-whale/starwhale/issues/751   
- [x] runtime dockerize
   - [x] https://github.com/star-whale/starwhale/issues/750
   - [x] #522
