### ISSUE TITLE
[#756 subtask] Refactor dataset index part based on the datastore

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#896]
https://github.com/star-whale/starwhale/issues/756

- Replace `swds_idx` with datastore.
  - In the Standalone instance:
     - use the datastore to put data, and scan the range data.
     - when copying the dataset to/from another instance, swcli will auto dump/load the `datastore` table parquet file.
  - In the Cloud instance:
     - When receiving/sending a new dataset, the controller will auto load/dump the standalone `datastore` table parquet file.
- Basic design points:
  - swds_label/annotation/index.jsonl was stored in the datastore.
  - one table represents one version of the specific dataset.
  - Table Schema:
    - TBD. 
- Probably Tasks:
  - [x] Design Table Schema
  - [x] Refactor dataset build process with datastore
  - [x] Remove `swds_label` and `index.jsonl`
  - [x] Refactor dataset load process with datastore
  - [ ] update version filed to v2 for dataset in the `_manifest.yaml`
  - [ ] Refactor copy command for standalone -> cloud that needs dump json file
