### ISSUE TITLE
[#756 subtask] support index-only dataset

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#897]
https://github.com/star-whale/starwhale/issues/756

- no generate `swds_bin`, use the raw data that may locate at local(local disk) or remote storage(s3). 
- Starwhale dataset composition:
  - Raw data
    - Examples: images, videos, audio, string text, JSON files, and other bin files.
    - Format:
       -  `swds_bin`: a binary format designed by Starwhale that owns chunked data, high efficiency, and storeage-friendly features.
       - raw data: 
         - local access: in the local storage
         - remote access: in the remote s3 storage
  - Label-Index data 
    - Example: label, annotation, etc. 
    - Format:
      - Starwhale datastore. Different instances have different implementations, but the API is unified.
- Probably Tasks:
  - [x] Tune dataset build and load process for the index-only purpose.
     - [x] raw data in starwhale object-storage: https://github.com/star-whale/starwhale/pull/918
     - [x] raw data in other storage: local disk, s3 : https://github.com/star-whale/starwhale/pull/944
  - [x] Define a link type for raw data. https://github.com/star-whale/starwhale/pull/944
  - [x] Define some environments for authority info that inject by the runtime phase. https://github.com/star-whale/starwhale/pull/944
